name: Testing
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=cagiti/jenkins
        VERSION="2.263.3-lts"
        if [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=${VERSION}.pr-${{ github.event.number }}
        fi
        TAG="${DOCKER_IMAGE}:${VERSION}"
        echo ::set-output name=image_name::${DOCKER_IMAGE}
        echo ::set-output name=tag::${VERSION}
        echo ::set-output name=image::${TAG}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.prep.outputs.image }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Build Chart
      run: helm dependency build cijenkinsio

    - name: Run chart-testing (lint)
      run: helm lint cijenkinsio

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.1.0

    - name: Deploy Chart
      run: helm upgrade --install --wait --set jenkins.controller.image=${{ steps.prep.outputs.image_name }} --set jenkins.controller.tag=${{ steps.prep.outputs.tag }} --timeout 10m cijenkinsio cijenkinsio --debug

    - name: Test Chart
      run: helm test cijenkinsio

    - name: Test Logs
      run: kubectl logs cijenkinsio-test-connection
