name: "Update Center"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  updatecenter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Update
      uses: docker://garethjevans/uc:main
      with:
        entrypoint: uc
        args: update --path plugins.txt --jenkins-version 2.263.1 --display-updates-only

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update plugin versions
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: update_plugins
        delete-branch: true
        title: 'chore: Update plugin versions'
        body: |
          Update plugin versions
        labels: |
          on_hold
        assignees: cagiti
        reviewers: cagiti
        draft: false
